services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt && playwright install chromium"
    startCommand: "python app.py"
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
